var files =
[
    [ "About.h", "About_8h.html", null ],
    [ "access.h", "access_8h.html", "access_8h" ],
    [ "AnalyticPropagator.h", "AnalyticPropagator_8h.html", null ],
    [ "arraybse.cpp", "arraybse_8cpp.html", "arraybse_8cpp" ],
    [ "arraybse.h", "arraybse_8h.html", "arraybse_8h" ],
    [ "arraygph.cpp", "arraygph_8cpp.html", null ],
    [ "arrayops.cpp", "arrayops_8cpp.html", null ],
    [ "arrayutl.cpp", "arrayutl_8cpp.html", null ],
    [ "Attitude.cpp", "Attitude_8cpp.html", null ],
    [ "Attitude.h", "Attitude_8h.html", "Attitude_8h" ],
    [ "AttitudeHistory.cpp", "AttitudeHistory_8cpp.html", null ],
    [ "AttitudeHistory.h", "AttitudeHistory_8h.html", null ],
    [ "AttitudeSimulatorServer.cpp", "AttitudeSimulatorServer_8cpp.html", "AttitudeSimulatorServer_8cpp" ],
    [ "AttitudeState.cpp", "AttitudeState_8cpp.html", null ],
    [ "AttitudeState.h", "AttitudeState_8h.html", "AttitudeState_8h" ],
    [ "blas.cpp", "blas_8cpp.html", "blas_8cpp" ],
    [ "blas.h", "blas_8h.html", "blas_8h" ],
    [ "blasimpexp.h", "blasimpexp_8h.html", "blasimpexp_8h" ],
    [ "bnengine.h", "bnengine_8h.html", [
      [ "CAMbinaryEngine", "classCAMbinaryEngine.html", "classCAMbinaryEngine" ]
    ] ],
    [ "camlaimpexp.h", "camlaimpexp_8h.html", "camlaimpexp_8h" ],
    [ "cammva.h", "cammva_8h.html", null ],
    [ "camtype.h", "camtype_8h.html", [
      [ "CAMType", "classCAMType.html", "classCAMType" ]
    ] ],
    [ "cblasimpexp.h", "cblasimpexp_8h.html", "cblasimpexp_8h" ],
    [ "CentralBody.cpp", "CentralBody_8cpp.html", null ],
    [ "CentralBody.h", "CentralBody_8h.html", null ],
    [ "CodingStandards.h", "CodingStandards_8h.html", null ],
    [ "CombinedNumericPropagator.cpp", "CombinedNumericPropagator_8cpp.html", null ],
    [ "CombinedNumericPropagator.h", "CombinedNumericPropagator_8h.html", [
      [ "CombinedNumericPropagator", "classO__SESSAME_1_1CombinedNumericPropagator.html", "classO__SESSAME_1_1CombinedNumericPropagator" ]
    ] ],
    [ "CommentStandards.h", "CommentStandards_8h.html", null ],
    [ "d_lg10.c", "d__lg10_8c.html", "d__lg10_8c" ],
    [ "d_sign.c", "d__sign_8c.html", "d__sign_8c" ],
    [ "darray.cpp", "darray_8cpp.html", null ],
    [ "darray.h", "darray_8h.html", [
      [ "CAMdoubleArray", "classCAMdoubleArray.html", "classCAMdoubleArray" ]
    ] ],
    [ "dasum.c", "dasum_8c.html", "dasum_8c" ],
    [ "datahndl.cpp", "datahndl_8cpp.html", "datahndl_8cpp" ],
    [ "datahndl.h", "datahndl_8h.html", "datahndl_8h" ],
    [ "daxpy.c", "daxpy_8c.html", "daxpy_8c" ],
    [ "dbengnea.cpp", "dbengnea_8cpp.html", null ],
    [ "dbengneb.cpp", "dbengneb_8cpp.html", null ],
    [ "dcopy.c", "dcopy_8c.html", "dcopy_8c" ],
    [ "ddot.c", "ddot_8c.html", "ddot_8c" ],
    [ "dgecon.c", "dgecon_8c.html", "dgecon_8c" ],
    [ "dgeequ.c", "dgeequ_8c.html", "dgeequ_8c" ],
    [ "dgemm.c", "dgemm_8c.html", "dgemm_8c" ],
    [ "dgemv.c", "dgemv_8c.html", "dgemv_8c" ],
    [ "dger.c", "dger_8c.html", "dger_8c" ],
    [ "dgerfs.c", "dgerfs_8c.html", "dgerfs_8c" ],
    [ "dgesvx.c", "dgesvx_8c.html", "dgesvx_8c" ],
    [ "dgetf2.c", "dgetf2_8c.html", "dgetf2_8c" ],
    [ "dgetrf.c", "dgetrf_8c.html", "dgetrf_8c" ],
    [ "dgetrs.c", "dgetrs_8c.html", "dgetrs_8c" ],
    [ "dlabad.c", "dlabad_8c.html", "dlabad_8c" ],
    [ "dlacon.c", "dlacon_8c.html", "dlacon_8c" ],
    [ "dlacpy.c", "dlacpy_8c.html", "dlacpy_8c" ],
    [ "dlamch.c", "dlamch_8c.html", "dlamch_8c" ],
    [ "dlange.c", "dlange_8c.html", "dlange_8c" ],
    [ "dlaqge.c", "dlaqge_8c.html", "dlaqge_8c" ],
    [ "dlassq.c", "dlassq_8c.html", "dlassq_8c" ],
    [ "dlaswp.c", "dlaswp_8c.html", "dlaswp_8c" ],
    [ "dlatrs.c", "dlatrs_8c.html", "dlatrs_8c" ],
    [ "dmatrix.cpp", "dmatrix_8cpp.html", null ],
    [ "dmatrix.h", "dmatrix_8h.html", "dmatrix_8h" ],
    [ "dnrm2.c", "dnrm2_8c.html", "dnrm2_8c" ],
    [ "drot.c", "drot_8c.html", "drot_8c" ],
    [ "drscl.c", "drscl_8c.html", "drscl_8c" ],
    [ "dscal.c", "dscal_8c.html", "dscal_8c" ],
    [ "dswap.c", "dswap_8c.html", "dswap_8c" ],
    [ "dsymv.c", "dsymv_8c.html", "dsymv_8c" ],
    [ "dsyr2.c", "dsyr2_8c.html", "dsyr2_8c" ],
    [ "dsyr2k.c", "dsyr2k_8c.html", "dsyr2k_8c" ],
    [ "dtrmm.c", "dtrmm_8c.html", "dtrmm_8c" ],
    [ "dtrmv.c", "dtrmv_8c.html", "dtrmv_8c" ],
    [ "dtrsm.c", "dtrsm_8c.html", "dtrsm_8c" ],
    [ "dtrsv.c", "dtrsv_8c.html", "dtrsv_8c" ],
    [ "dvector.h", "dvector_8h.html", "dvector_8h" ],
    [ "EarthCentralBody.cpp", "EarthCentralBody_8cpp.html", null ],
    [ "EarthCentralBody.h", "EarthCentralBody_8h.html", "EarthCentralBody_8h" ],
    [ "Environment.cpp", "Environment_8cpp.html", null ],
    [ "Environment.h", "Environment_8h.html", "Environment_8h" ],
    [ "camblas/f2c.h", "camblas_2f2c_8h.html", "camblas_2f2c_8h" ],
    [ "camlapack/f2c.h", "camlapack_2f2c_8h.html", "camlapack_2f2c_8h" ],
    [ "Functor.h", "Functor_8h.html", null ],
    [ "GravityFunctions.h", "GravityFunctions_8h.html", "GravityFunctions_8h" ],
    [ "History.cpp", "History_8cpp.html", null ],
    [ "History.h", "History_8h.html", "History_8h" ],
    [ "HokieSatSimulation.cpp", "HokieSatSimulation_8cpp.html", "HokieSatSimulation_8cpp" ],
    [ "HokieSatSimulation.h", "HokieSatSimulation_8h.html", "HokieSatSimulation_8h" ],
    [ "i_dnnt.c", "i__dnnt_8c.html", "i__dnnt_8c" ],
    [ "idamax.c", "idamax_8c.html", "idamax_8c" ],
    [ "camblas/ilaenv.c", "camblas_2ilaenv_8c.html", "camblas_2ilaenv_8c" ],
    [ "camlapack/ilaenv.c", "camlapack_2ilaenv_8c.html", "camlapack_2ilaenv_8c" ],
    [ "Intallation.h", "Intallation_8h.html", null ],
    [ "Integrator.h", "Integrator_8h.html", "Integrator_8h" ],
    [ "Interpolator.h", "Interpolator_8h.html", "Interpolator_8h" ],
    [ "Introduction.h", "Introduction_8h.html", null ],
    [ "Keplerian.cpp", "Keplerian_8cpp.html", null ],
    [ "Keplerian.h", "Keplerian_8h.html", "Keplerian_8h" ],
    [ "License.h", "License_8h.html", null ],
    [ "LinearInterpolator.cpp", "LinearInterpolator_8cpp.html", null ],
    [ "LinearInterpolator.h", "LinearInterpolator_8h.html", null ],
    [ "lsame.c", "lsame_8c.html", "lsame_8c" ],
    [ "MagneticModel.h", "MagneticModel_8h.html", [
      [ "MagneticFieldCoefficients", "structO__SESSAME_1_1MagneticFieldCoefficients.html", "structO__SESSAME_1_1MagneticFieldCoefficients" ]
    ] ],
    [ "Mainpage.h", "Mainpage_8h.html", null ],
    [ "matbse.cpp", "matbse_8cpp.html", "matbse_8cpp" ],
    [ "matbse.h", "matbse_8h.html", "matbse_8h" ],
    [ "matgph.cpp", "matgph_8cpp.html", null ],
    [ "MathUtils.h", "MathUtils_8h.html", "MathUtils_8h" ],
    [ "Matrix.h", "Matrix_8h.html", "Matrix_8h" ],
    [ "matutl.cpp", "matutl_8cpp.html", null ],
    [ "mvaexit.cpp", "mvaexit_8cpp.html", "mvaexit_8cpp" ],
    [ "mvaexit.h", "mvaexit_8h.html", "mvaexit_8h" ],
    [ "mvagph.cpp", "mvagph_8cpp.html", "mvagph_8cpp" ],
    [ "mvagph.h", "mvagph_8h.html", [
      [ "CAMmvaGraphics", "classCAMmvaGraphics.html", "classCAMmvaGraphics" ]
    ] ],
    [ "mvaimpexp.h", "mvaimpexp_8h.html", "mvaimpexp_8h" ],
    [ "mvalngbase.cpp", "mvalngbase_8cpp.html", "mvalngbase_8cpp" ],
    [ "mvalngbase.h", "mvalngbase_8h.html", [
      [ "MVAlongBase", "classMVAlongBase.html", "classMVAlongBase" ]
    ] ],
    [ "mvasamp1.cpp", "mvasamp1_8cpp.html", "mvasamp1_8cpp" ],
    [ "mvasamp2.cpp", "mvasamp2_8cpp.html", "mvasamp2_8cpp" ],
    [ "mvasamp3.cpp", "mvasamp3_8cpp.html", "mvasamp3_8cpp" ],
    [ "mvasamp4.cpp", "mvasamp4_8cpp.html", "mvasamp4_8cpp" ],
    [ "NumericPropagator.cpp", "NumericPropagator_8cpp.html", null ],
    [ "NumericPropagator.h", "NumericPropagator_8h.html", [
      [ "NumericPropagator", "classO__SESSAME_1_1NumericPropagator.html", "classO__SESSAME_1_1NumericPropagator" ]
    ] ],
    [ "Orbit.cpp", "Orbit_8cpp.html", null ],
    [ "Orbit.h", "Orbit_8h.html", "Orbit_8h" ],
    [ "OrbitFrame.cpp", "OrbitFrame_8cpp.html", null ],
    [ "OrbitFrame.h", "OrbitFrame_8h.html", null ],
    [ "OrbitFrameECEF.cpp", "OrbitFrameECEF_8cpp.html", null ],
    [ "OrbitFrameECEF.h", "OrbitFrameECEF_8h.html", null ],
    [ "OrbitFrameEQW.h", "OrbitFrameEQW_8h.html", null ],
    [ "OrbitFrameIJK.h", "OrbitFrameIJK_8h.html", null ],
    [ "OrbitFrameNTW.h", "OrbitFrameNTW_8h.html", [
      [ "OrbitFrameNTW", "classOrbitFrameNTW.html", "classOrbitFrameNTW" ]
    ] ],
    [ "OrbitFramePQW.h", "OrbitFramePQW_8h.html", null ],
    [ "OrbitFrameRSW.h", "OrbitFrameRSW_8h.html", null ],
    [ "OrbitFrameSEZ.h", "OrbitFrameSEZ_8h.html", null ],
    [ "OrbitHistory.cpp", "OrbitHistory_8cpp.html", null ],
    [ "OrbitHistory.h", "OrbitHistory_8h.html", null ],
    [ "OrbitState.cpp", "OrbitState_8cpp.html", null ],
    [ "OrbitState.h", "OrbitState_8h.html", null ],
    [ "OrbitStateRepresentation.cpp", "OrbitStateRepresentation_8cpp.html", null ],
    [ "OrbitStateRepresentation.h", "OrbitStateRepresentation_8h.html", null ],
    [ "Plot.cpp", "Plot_8cpp.html", null ],
    [ "Plot.h", "Plot_8h.html", "Plot_8h" ],
    [ "PositionVelocity.cpp", "PositionVelocity_8cpp.html", null ],
    [ "PositionVelocity.h", "PositionVelocity_8h.html", "PositionVelocity_8h" ],
    [ "pow_di.c", "pow__di_8c.html", "pow__di_8c" ],
    [ "Propagator.cpp", "Propagator_8cpp.html", null ],
    [ "Propagator.h", "Propagator_8h.html", null ],
    [ "QuaternionAngVelDynamics.h", "QuaternionAngVelDynamics_8h.html", "QuaternionAngVelDynamics_8h" ],
    [ "QuaternionDynamics.h", "QuaternionDynamics_8h.html", "QuaternionDynamics_8h" ],
    [ "QuaternionKinematics.h", "QuaternionKinematics_8h.html", "QuaternionKinematics_8h" ],
    [ "range.cpp", "range_8cpp.html", "range_8cpp" ],
    [ "range.h", "range_8h.html", [
      [ "CAMrange", "classCAMrange.html", "classCAMrange" ]
    ] ],
    [ "rangetst1.cpp", "rangetst1_8cpp.html", "rangetst1_8cpp" ],
    [ "Rotation.cpp", "Rotation_8cpp.html", null ],
    [ "Rotation.h", "Rotation_8h.html", "Rotation_8h" ],
    [ "RungeKutta.h", "RungeKutta_8h.html", "RungeKutta_8h" ],
    [ "RungeKuttaFehlbergIntegrator.cpp", "RungeKuttaFehlbergIntegrator_8cpp.html", null ],
    [ "RungeKuttaFehlbergIntegrator.h", "RungeKuttaFehlbergIntegrator_8h.html", null ],
    [ "RungeKuttaIntegrator.cpp", "RungeKuttaIntegrator_8cpp.html", null ],
    [ "RungeKuttaIntegrator.h", "RungeKuttaIntegrator_8h.html", null ],
    [ "camblas/s_cmp.c", "camblas_2s__cmp_8c.html", "camblas_2s__cmp_8c" ],
    [ "camlapack/s_cmp.c", "camlapack_2s__cmp_8c.html", "camlapack_2s__cmp_8c" ],
    [ "camblas/s_copy.c", "camblas_2s__copy_8c.html", "camblas_2s__copy_8c" ],
    [ "camlapack/s_copy.c", "camlapack_2s__copy_8c.html", "camlapack_2s__copy_8c" ],
    [ "SampleFile.cpp", "SampleFile_8cpp.html", "SampleFile_8cpp" ],
    [ "SolarDisturbances.h", "SolarDisturbances_8h.html", "SolarDisturbances_8h" ],
    [ "strctbse.cpp", "strctbse_8cpp.html", "strctbse_8cpp" ],
    [ "strctbse.h", "strctbse_8h.html", [
      [ "CAMstructureBase", "classCAMstructureBase.html", "classCAMstructureBase" ]
    ] ],
    [ "testAttitudeIntegration.cpp", "testAttitudeIntegration_8cpp.html", "testAttitudeIntegration_8cpp" ],
    [ "testDynamics.cpp", "testDynamics_8cpp.html", "testDynamics_8cpp" ],
    [ "testEnvironment.cpp", "testEnvironment_8cpp.html", "testEnvironment_8cpp" ],
    [ "testIntegration.cpp", "testIntegration_8cpp.html", "testIntegration_8cpp" ],
    [ "testInterface.cpp", "testInterface_8cpp.html", "testInterface_8cpp" ],
    [ "testMatrix.cpp", "testMatrix_8cpp.html", "testMatrix_8cpp" ],
    [ "testOrbitIntegration.cpp", "testOrbitIntegration_8cpp.html", "testOrbitIntegration_8cpp" ],
    [ "testPropagation.cpp", "testPropagation_8cpp.html", "testPropagation_8cpp" ],
    [ "testRotation.cpp", "testRotation_8cpp.html", "testRotation_8cpp" ],
    [ "ThirdBodyDisturbances.h", "ThirdBodyDisturbances_8h.html", "ThirdBodyDisturbances_8h" ],
    [ "TiltedDipoleMagneticModel.cpp", "TiltedDipoleMagneticModel_8cpp.html", null ],
    [ "TiltedDipoleMagneticModel.h", "TiltedDipoleMagneticModel_8h.html", null ],
    [ "Time.cpp", "Time_8cpp.html", "Time_8cpp" ],
    [ "Time.h", "Time_8h.html", "Time_8h" ],
    [ "TimeCompat.cpp", "TimeCompat_8cpp.html", "TimeCompat_8cpp" ],
    [ "Tutorials.h", "Tutorials_8h.html", null ],
    [ "TwoBodyDynamics.h", "TwoBodyDynamics_8h.html", "TwoBodyDynamics_8h" ],
    [ "typehndl.h", "typehndl_8h.html", "typehndl_8h" ],
    [ "under.cpp", "under_8cpp.html", null ],
    [ "under.h", "under_8h.html", [
      [ "CAMunderscore", "classCAMunderscore.html", "classCAMunderscore" ]
    ] ],
    [ "UsingFramework.h", "UsingFramework_8h.html", null ],
    [ "vecbse.cpp", "vecbse_8cpp.html", "vecbse_8cpp" ],
    [ "vecbse.h", "vecbse_8h.html", "vecbse_8h" ],
    [ "vecgph.cpp", "vecgph_8cpp.html", null ],
    [ "vecutl.cpp", "vecutl_8cpp.html", null ],
    [ "xerbla.c", "xerbla_8c.html", "xerbla_8c" ]
];